name: Paying It Forward Podcast
favicon: null
layout_spectrum: 0.1770957917906344
typography_spectrum: 0.11640690686181188
title: Paying It Forward Podcast
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f86ac'
    - '#ffffff'
    - '#000000'
    - '#0000ff'
    - '#00ffff'
  brandStrength: 0.8125
  lightness: 0.614232309628278
  saturation: 0.03123541478998959
  rhythmicContrast: 0.9236928250174969
purpose: []
